apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    app: {{ include "currentmoscowtime.fullname" . }}
    chart: {{ include "currentmoscowtime.chart" . }}
type: Opaque
data:
  username: {{ default "" .Values.secrets.username | b64enc | quote }}