apiVersion: apps/v1
kind: Deployment
metadata:
  name: currentmoscowtime
  labels:
    app: currentmoscowtime
spec:
  replicas: 3
  selector:
    matchLabels:
      app: currentmoscowtime
  template:
    metadata:
      labels:
        app: currentmoscowtime
    spec:
      containers:
        - name: currentmoscowtime
          image: danielatonge/continuous_integration:latest
          ports:
            - containerPort: 3000