apiVersion: apps/v1
kind: Deployment
metadata:
  name: current-moscow-time
  labels:
    app: current-moscow-time
spec:
  replicas: 3
  selector:
    matchLabels:
      app: current-moscow-time
  template:
    metadata:
      labels:
        app: current-moscow-time
    spec:
      containers:
        - name: current-moscow-time
          image: danielatonge/continuous_integration:latest
          ports:
            - containerPort: 3000