apiVersion: v1
kind: Service
metadata:
  name: current-moscow-time
spec:
  selector:
    app: current-moscow-time
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer