# Default values for currentmoscowtime.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: danielatonge/continuous_integration
  pullPolicy: IfNotPresent
  tag: "latest"
  port: 3000

secrets:
  name: currentmoscowtime-secret
  username: currentmoscowtime

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}


service:
  type: LoadBalancer
  port: 3000


resources:
  requests:
    cpu: ".2"
    memory: "100Mi"
  limits:
    cpu: ".5"
    memory: "256Mi"


nodeSelector: {}

tolerations: []

affinity: {}
