# Default values for currentmoscowtime.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: danielatonge/continuous_integration
  pullPolicy: IfNotPresent
  tag: "latest"
  port: 3000

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}


service:
  type: LoadBalancer
  port: 3000


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious


nodeSelector: {}

tolerations: []

affinity: {}
