# Default values for currentmoscowtime.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: danielatonge/continuous_integration
  pullPolicy: IfNotPresent
  tag: "latest"
  port: 3000

secrets:
  name: currentmoscowtime-secret
  username: currentmoscowtime

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}


service:
  name: currentmoscowtime-service
  type: LoadBalancer
  port: 3000


resources:
  requests:
    cpu: ".2"
    memory: "100Mi"
  limits:
    cpu: ".5"
    memory: "256Mi"

statefulSet:
  podManagementPolicy: "Parallel"
  volumeClaimTemplates:
    spec:
      storageClassName: "storage-class"
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 256M

nodeSelector: {}

tolerations: []

affinity: {}
